### PR TITLE
[AUTOMATIC BUMP] Updates purchases-hybrid-common to 4.4.4

### PR DESCRIPTION
**Pull request by RCGitBot**
**This is an automatic bump.**

Updates purchases-hybrid-common to 4.4.4

### CODE REVIEW

**Comment by durpy2** [comment]
@vegaro Noticing below error this morning. Is this a bug?

```
[INSTALL_PODS] [!] CocoaPods could not find compatible versions for pod "PurchasesHybridCommon":
[INSTALL_PODS]   In Podfile:
[INSTALL_PODS]     RNPurchases (from `../node_modules/react-native-purchases`) was resolved to 5.2.4, which depends on
[INSTALL_PODS]       PurchasesHybridCommon (= 4.4.4)
[INSTALL_PODS] None of your spec sources contain a spec satisfying the dependency: `PurchasesHybridCommon (= 4.4.4)`.
[INSTALL_PODS] You have either:
[INSTALL_PODS]  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
[INSTALL_PODS]  * mistyped the name or version.
[INSTALL_PODS]  * not added the source repo that hosts the Podspec to your Podfile.

```

**Comment by aboedo** [comment]
@durpy2 that is tied to a caching issue, try running `pod install --repo update` or `pod repo update && pod install`

**Comment by durpy2** [comment]
@aboedo Thank you. Unfortunately I'm using expo managed workflow with eas build, not sure how to run those commands during build step. I've also tried downgrading to version 5.2.2, interestingly the same error appears. Just curious, is the caching issue lie in CocoaPod servers? Does that mean this will resolve itself in few days?

**Comment by aboedo** [comment]
it'd be in the actual build server, sadly. I would imagine that it will resolve itself. 
One alternative you could try in the meantime if you have a mac is to make a development build, instructions are here: https://docs.expo.dev/development/create-development-builds/

**Comment by durpy2** [comment]
Thank you.

**Comment by Aryk** [comment]
@aboedo do you know roughly how long that may take? Like 24 hours or a week?

**Comment by Aryk** [comment]
@durpy2 try adding --clear-cache:

https://github.com/expo/expo/issues/15248#issuecomment-1263147327

**Pull request merged**
