### PR TITLE
Adds new Magic Weather sample app

### PR DESCRIPTION
**Pull request by codykerns**
This PR adds the new 'MagicWeather' sample app to a new /Examples folder (for platform consistency).

This doesn't address the existing 'example' folder.

### CODE REVIEW

**Review by rkotzy — APPROVED** [review]

**Comment by vegaro** [comment]
When I login with a user I get this warning which I honestly don't know what it means

image

**Review by vegaro — COMMENTED** [review]
Looks good besides the warning. I am going to look into that CircleCI failure and see what's up

**Comment by vegaro** [comment]
CircleCI failures fixed in https://github.com/RevenueCat/react-native-purchases/pull/214. When that's in, this PR can be rebased and the tests should start passing :)

**Comment by vegaro** [comment]
@codykerns https://github.com/RevenueCat/react-native-purchases/pull/214 has been merged, can you update this branch with develop?

**Pull request merged**
