### PR TITLE
`PaywallFooterViewManager`: added controller to UIVC hierarchy

### PR DESCRIPTION
**Pull request by NachoSoto**
This should fix the safe area issues.

### CODE REVIEW

**Review by tonidero — APPROVED** [review]

**Review by tonidero — COMMENTED** [review]
Seems tests are failing?

**Comment by vegaro** [comment]
I think this has broken the corners and the trick we are doing with the padding and marging in Javascript doesn't work anymore.

Screenshot 2024-01-12 at 12 02 57

**Comment by vegaro** [comment]
SafeAreaView looks correct though 

Screenshot 2024-01-12 at 12 05 29

**Comment by NachoSoto** [comment]
@vegaro not sure which branch you're working on. Feel free to merge this on `footer-view` whenever :)

**Pull request merged**
