### PR TITLE
Fixed MagicWeather and Xcode 12.5

### PR DESCRIPTION
**Pull request by vegaro**
Counterpart of https://github.com/RevenueCat/react-native-purchases/pull/258/files?file-filters%5B%5D=.json&file-filters%5B%5D=.yml&file-filters%5B%5D=No+extension for MagicWeather

### CODE REVIEW

**Review by aboedo — APPROVED** [review]

**Comment by aboedo** [comment]
looks like we also need to update the NDK version if we're using the new circleCI machien

**Comment by aboedo** [comment]
@vegaro this is ready to go, right?

**Comment by aboedo** [comment]
@vegaro I'm gonna go ahead and merge this one since other stuff needs it

**Comment by vegaro** [comment]
Thx @aboedo . I forgot I had this open

**Pull request merged**
