### PR TITLE
Note change from setUp to configure

### PR DESCRIPTION
**Pull request by swrobel**
This seems to have been missed from https://github.com/RevenueCat/react-native-purchases/pull/374

### CODE REVIEW

**Comment by NachoSoto** [comment]
Thanks for pointing this out!

**Review by NachoSoto — APPROVED** [review]

**Comment by NachoSoto** [comment]
I added this to [the release](https://github.com/RevenueCat/react-native-purchases/releases/tag/5.0.0-beta.1) as well.

**Comment by swrobel** [comment]
FYI it looks like this probably needs to be changed in [Changelog.latest.md](https://github.com/RevenueCat/react-native-purchases/blob/main/CHANGELOG.latest.md) as well (so many places!)

**Comment by NachoSoto** [comment]
Done in #391

**Pull request merged**
