### PR TITLE
Upgrade dependencies to fix CVEs

### PR DESCRIPTION
**Pull request by ethervoid**
Upgrade dependencies to fix vulnerabilities:

- yargs-parsed to 13.1.2
- ip to 2.0.1

### CODE REVIEW

**Comment by aboedo** [comment]
oops, I guess it does actually break yarn
@tonidero or @vegaro could you take a look?

**Comment by tonidero** [comment]
Sure! Will take a look tomorrow

**Comment by vegaro** [comment]
Opened https://github.com/RevenueCat/react-native-purchases/pull/927 which I think is the fix for yargs-parser

Still looking into the other one, because it involves upgrading react native

**Comment by vegaro** [comment]
Looks like the yargs-parser is gone with #927 . Just opened #928 which I think will fix the ip one

**Comment by vegaro** [comment]
This got closed automatically, but I think those other PRs are a more appropriate fix. I am still unsure the ip one is completely fix. I will see tomorrow

**Comment by ethervoid** [comment]
Thank you @vegaro @tonidero !

**Comment by vegaro** [comment]
Security issues are fixed now :)

**Pull request closed without merging**
