### PR TITLE
[final] fix a copy paste issue in an error message

### PR DESCRIPTION
**Pull request by aboedo**
* fix copy/paste issue in error message
* added `watch: true` to config so that when you run build it starts watching for changes and compiles typescript automatically.

### CODE REVIEW

**Comment by aboedo** [comment]
ouch, tests did not like this PR. @vegaro any thoughts on what might be going on? The changes seem fairly innoccuous

**Comment by vegaro** [comment]
Let me take a look

**Comment by vegaro** [comment]
It looks like it's running tsc, and therefore it just stays waiting for file changes. Why is it running tsc though? hmmmm

**Comment by vegaro** [comment]
Ok, so what's happening is that when doing `yarn install`, both `preinstall` and `prepublish` get run. It turns out that `prepublish` does `tsc`, so since we added the watch config, it just hangs forever waiting for changes, until CircleCI kills it.

I think instead of adding the watch flag, which also breaks our `prepublish` script, we should manually add the watch command `tsc **.ts --watch` to the `setup.example` script. Either that, or we add it to `build`, which would force us to run it manually at least once. What do you think?

**Comment by aboedo** [comment]
agreed 👍  I'll make the changes on Monday. Thanks for the help!

**Pull request merged**
